services:
  db:
    image: postgres:15
    container_name: banco-barbearia
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha-barbearia-banco
      POSTGRES_DB: barbearia_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  api:
    build: .
    container_name: api-barbearia
    restart: always
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      # URL apontando para o serviço "db"
      DATABASE_URL: "postgresql://admin:senha-barbearia-banco@db:5432/barbearia_db?schema=public"
      JWT_SECRET: "sua_chave_secreta_aqui"
    depends_on:
      - db
        
volumes:
  postgres_data: